### PR TITLE
Improve visualization of PCA results

### PR DESCRIPTION
**Pull request by btjanaka**
The plot showing results of PCA are now interactive - when hovering over
the points with a mouse, the index and molecular formula are displayed
in a yellow box, while the 1D scan for the molecule is displayed in a
figure below the main plot. This allows us to better understand what PCA
is doing.

### CODE REVIEW

**Comment by jmaat** [comment]
Wow! Okay I have a few questions, I tried loading your notebook and the plot. It's pretty awesome!

I do have a concern though. Here is a screenshot of the plot I am seeing: 
Screen Shot 2019-10-12 at 12 17 26 AM

In figure 2, what is this plot? Is improper angle versus energy? If yes, does this cover the enter 21 frames? If so, this doesn't look how I predicted.

**Comment by btjanaka** [comment]
Yes, Figure 2 should be a plot of all 21 normalized energies vs improper angle. It plots the energies for frame 0, 1,...,20

**Comment by jmaat** [comment]
For example, these cases ...
image
image
image
look really odd. We should be seeing more symmetric parabolic shapes with either a single wide minima or a double well. Can you double check the plots in figure 2 are really the plotted results for the grid optimizations? How are you zeroing the energies?

Was expecting trends to look more like this or this:
image
image

**Comment by jmaat** [comment]
Ok I think I'm seeing the issue. The steps for the grid optimizations should be the following improper angles:
         "steps": [
            -40,
            -36,
            -32,
            -28,
            -24,
            -20,
            -16,
            -12,
            -8,
            -4,
            0,
            4,
            8,
            12,
            16,
            20,
            24,
            28,
            32,
            36,
            40
          ],

Either the calculations were incorrectly restraining the improper angles from -40 to 40 or the plots are just cutting off at around 20 degrees. 
image

**Comment by btjanaka** [comment]
Something to keep in mind is that the plot only shows "GOOD_ENTRIES" - i.e. it only shows molecules that had the correct number of frames, so indices may differ from the original ENTRIES vector.

Also, I sometimes had issues where the plot did not update immediately when I moused over it, so make sure it is not showing a plot from another value.

**Comment by btjanaka** [comment]
I am normalizing by subtracting the minimum energy. Even if energy is negative, I think this should still be fine?

I'll also add that some of the plots _do_ look like the ones you mentioned above.

**Comment by btjanaka** [comment]
@jmaat I have updated the plots - they should be much clearer now. The plots still do not update immediately, but at least now they let you know which molecule you are on, and they are much larger and clearer.

I also added some basic clustering - will work on showing all the plots together.

**Pull request closed without merging**
